# Generated by Django 5.2.6 on 2025-09-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examen', models.CharField(max_length=100)),
                ('pregunta_numero', models.IntegerField()),
                ('respuesta_seleccionada', models.IntegerField()),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
