# Generated by Django 5.2.6 on 2025-09-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestaexamen',
            name='respuesta_seleccionada',
            field=models.CharField(max_length=100),
        ),
    ]
